version: "3"

services:
  batch:
    image: node:17
    container_name: batch
    working_dir: /usr/src/batch
    volumes:
      - ../batch:/usr/src/batch
      - dummy:/usr/src/batch/node_modules
    profiles:
      - batch

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dummy:
