version: "3"

services:
  batch:
    image: node:17
    container_name: batch
    working_dir: /usr/src/batch
    volumes:
      - ../batch:/usr/src/batch
      - dummy:/usr/src/batch/node_modules

volumes:
  dummy:
